### ISSUE TITLE
Create a new tab on Twitter for Gender navigation specifically

### ISSUE THREAD

**Issue by mvidonne** [hestiaAI/hestialabs-experiences#1007]
For ads with "targetingType" : "Gender",  I would like
for 
1 "targetingValue" : "Men"
2 "targetingValue" : "women"
count how many are targeting me through Gender (M/W) and  percentage of all ads
what were the criteria?  
by keywords, interest, Follower look-alikes, Interest and conversation topics
ex 
"targetingValue" : "Men"    --> "targetingType" : "Interests" "targetingValue" : "Leadership"   x time
"targetingValue" : "Women" --> "targetingType" : "Interests" "targetingValue" : "Fashion"   x time

are there common criteria between the 2 Gender

**Comment by mvidonne** [comment]
@Shalf any comment?

**Comment by pdehaye** [comment]
Dev resources are previous and should be allocated according to a structured process.

**Comment by Shalf** [comment]
Am a bit puzzled here. There is a momentum on Twitter with specific targeting (ads, semi-automated moderation, coordinated raids by masculinists) issues at women.

Shouldn't that kind of enhancement proposal be reviewed by devs, and for instance in that case, put into "backlog" at least, instead of closing and asserting (falsely imho) this is not even a topic?
I get the "not urgent". And this could be important.

**Comment by pdehaye** [comment]
I didn't say it was not a topic. It is. And yes it could be important. 

I commented on the process, which certainly is not that @mvidonne submits an issue and then draws you in this.

**Comment by Shalf** [comment]
So that should have been a "discussion" gituub-wise, and not an "issue", and should we transform it into one?

MP and did had a short coffee-break prep-talk about this before she posted, so on my side, it was OK and fekt organic regarding process.

Broader scope:
Where on Hestia's github (and is github the right tool, providing webhooks and sending issues to devs is taken care of) should biz people talk about their stuff (before it begins a company/dev topic, and above all if it never needs to become one)?

**Comment by Shalf** [comment]
Yes, transforming after "broader scope" in its own discussion 😏

**Comment by Shalf** [comment]
Back on topic, why I was asked to contribute here:

My wife and friends are considering starting a data collective re: twitter moderation/censure on women (with or without PDIO); I'd contribute, and LQDN's lawyer Alexis Fitzjean Ó Cobhthaigh would too, once the Technopolice collective "plainte collective" on vidéosurveillance is on the right track (filled in yesterday).

Hence my involvement.

**Comment by pdehaye** [comment]
> Broader scope:
> Where on Hestia's github (and is github the right tool, providing webhooks and sending issues to devs is taken care of) should biz people talk about their stuff (before it becomes a company/dev topic, and above all if it never needs to become one)?

On the clients github. And this might get promoted to the main board and given visibility to dev when deemed relevant by bizdev - and only then.

**Comment by Shalf** [comment]
Request to move this to "clients" to be quietly and privately upcycled there please.

**Comment by mvidonne** [comment]
Another perspective for all Horizon Europe grants:
MANDATORY: explaining how the gender dimension relates to the content of the planned research and innovation activities
