### ISSUE TITLE
sql-wasm.wasm fails to load in Chrome browsers

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#1016]
as deployed at 

https://test.hestialabs.org/experience/twitter#load-data

When you try and load the sample file

You get
![Screenshot 2022-09-28 at 15 03 07](https://user-images.githubusercontent.com/1473244/192801384-8377a57e-c86b-4419-b567-df175f600624.png)

This happens on:

- chrome/windows
- brave/macos
- safari/macos

This does not happen on:

- firefox/windows

**Comment by andreaskundig** [comment]
curl fails
```
curl 'https://test.hestialabs.org/_nuxt/node_modules/sql.js/dist/sql-wasm.020d507.wasm'
```

but this curl command works. Presumably we need to specify some header for wasm in the netlify.toml redirections
```
curl 'https://test.hestialabs.org/_nuxt/node_modules/sql.js/dist/sql-wasm.020d507.wasm' -H 'Accept-Encoding: gzip, deflate, br'
```

**Comment by andreaskundig** [comment]
https://web.dev/loading-wasm/

> The server must be configured to serve the .wasm file with the correct MIME type by sending the Content-Type: application/wasm header.

**Comment by valentinoli** [comment]
Assigned to @andreaskundig

**Comment by alexbfree** [comment]
On test.hestialabs.org this is happening and blocking use of Twitter, Instagram and Tinder experiences so far. Not Uber or LinkedIn.

**Comment by andreaskundig** [comment]
I redeployed a new version and the problem is gone. I have no idea why it didn't work before.

**Comment by andreaskundig** [comment]
Uber and Linkedin probably don't use the sql pipeline.

**Comment by andreaskundig** [comment]
On digipower.academy, where it works in chrome, the file doesn't give a 404
```
curl https://digipower.academy/_nuxt/node_modules/sql.js/dist/sql-wasm.020d507.wasm -i
HTTP/2 200
accept-ranges: bytes
age: 0
cache-control: public, max-age=0, must-revalidate
content-type: application/wasm
date: Thu, 29 Sep 2022 15:40:42 GMT
etag: "cab8ea991235a53e48a7bacc5aba1141-ssl"
server: Netlify
strict-transport-security: max-age=31536000
x-nf-request-id: 01GE4YGFETHT0NX034EVNG0N21
content-length: 608663
```

**Comment by alexbfree** [comment]
Confirmed, it works now. Thanks @andreaskundig. Closing.

**Comment by andreaskundig** [comment]
# The wasm file is missing!

This file is present in the build deployed at digipower.academy, but not in the more recent builds we did on netlify-test

    experiences/dist/_nuxt/node_modules/sql.js/dist/sql-wasm.020d507.wasm

I parked the most recent build at netlify-test-broken. You can [see ](https://github.com/hestiaAI/hestialabs-experiences/tree/netlify-test-broken/experiences/dist/_nuxt) that `experiences/dist/_nuxt/node_modules` is missing.

The application can continue working if you have used the application before because the file is stored in an application cache. That cache is not cleared when you empty or disable the browser cache ! In chrome you can see that magic cache storage in the developer tools: Application > Cache > Cache storage

**Comment by andreaskundig** [comment]
fixed in ef11854

**Comment by HaixinShi** [comment]
@alexbfree will test and close it

**Comment by alexbfree** [comment]
Confirmed fixed. Thanks.
