### ISSUE TITLE
💡 [FEATURE REQUEST] Add "future" tabs to experiences

### ISSUE THREAD

**Issue by fquellec** [hestiaAI/hestialabs-experiences#1127]
**Is your feature request related to a problem? Please describe.**
Sometimes we need to show future features during demonstrations.

**Describe the solution you'd like**
We could add disabled tabs to the experience, the user would only see the title, we need a way to make it clear what these tabs are. For example, we could simply add "(SOON)" to the title when a tab is disabled.

**Comment by foucault-dumas** [comment]
We want the user to see more than the title, we want the user to see the future feature as well. We just have to make it clear that it's still under construction and will be available soon.
It all started with https://github.com/hestiaAI/hestialabs-experiences/issues/1115, it's a shame to show this new feature with a slide in a presentation rather than with a tab not yet active directly in the experience.

**Comment by pdehaye** [comment]
We could grey out the whole layout of that tab.

**Comment by fquellec** [comment]
@valentinoli suggest we could use Vuetify overlay to "disable" the tab, we could then show an image of the future feature with the overlay, or just a message saying that it's coming or we could use a skeleton loader that will show up each time we have new features.

**Comment by fquellec** [comment]
Also we have to keep in mind that sometimes making the mockup and integrating it to the experience as "future tab" is as long as actually implementing it directly.

**Comment by fquellec** [comment]
Closing as done in https://github.com/hestiaAI/hestialabs-experiences/pull/1136
