### ISSUE TITLE
⚜️ [EXPERIENCE REQUEST]: Collective LinkedIn experience

### ISSUE THREAD

**Issue by pdehaye** [hestiaAI/hestialabs-experiences#1141]
### ⚠️ Data for Development

[data set](https://193995.connect.drive.infomaniak.com/index.php/f/00038856)

### Title

Collective LinkedIn experience

### Subtitle

Unlock the power of Linkedin data

### Icon

<use same logo>

### Data Samples

I'm ok for [that](https://193995.connect.drive.infomaniak.com/index.php/f/00038856) to become the data sample for the [individual Linkedin experience](https://digipower.academy/experience/linkedin) as soon as the 2670 contact names are changed and their "position" and "company" randomly redistributed. Does anyone have a second dataset that can be used to illustrate this aggregated experiment?

### Collaborator

The Eyeballs Collective

#### Inferences about your group
The cards below represent the inferences (positive or negative) that Linkedin has made about the members of your group, classified according to the number of occurrences (from the most present to the least present inference).
-> indicate at the top the number of data sets analyzed
-> indicate on each card the number of occurrences and the percentage that it represents/the total number of data sets

#### Skills and diversity
The charts below represent the criteria Linkedin uses to determine which ads to show to your group members. They draw an interesting map of the skills and experiences of your group and its diversity.

Skills
- graph of "Member skills" ranked from most to least occurrences

Seniority
- graph of " job seniorities " ranked from most to least occurrences
- graph of "years of experience" ranked from most to least occurrences

Education
- graph of " Degrees " ranked from the most to the least occurrences
- "Fields of Study" graph sorted from the most to the least number of occurrences
- graph of "Member schools" ranked from most to least occurrences

#### Collective network ( Reach )
This infographic represents the scope of your group's network. Clicking on an item will filter all the graphs according to this criterion.

Evolution of the number of connections of your group
- Total number of contacts accumulated over time / number of deduplicated contacts accumulated over time

Employers of your contacts
- graph of the "companies" from the most to the least represented
(Add a "hide unknown" button and a "see the whole list" button)

Jobs of your contacts
- position" graph from the most to the least represented
(Add a "hide unknown" button and a "view entire list" button)

### Do you want to internationalize the experience?

- [x] Yes

### Data Portal Link

[here](https://www.linkedin.com/mypreferences/d/categories/privacy)

### Data Portal Instructions (HTML)

[here](https://github.com/hestiaAI/data-catalog/blob/main/workshop/linkedin.md)

**Comment by pdehaye** [comment]
Make sure to have a look at https://github.com/hestiaAI/clients/issues/82 to get a better sense of motivation and deadlines.

**Comment by foucault-dumas** [comment]
Thanks to this aggregated exp, a company would be able to identify: 

1. its strengths, weaknesses and differentiating elements, which implies that Hestia "adds up" data at each use to be able to compare the aggregate result of company X to all those already generated by previous companies. Examples:

- "your company has twice as many Active contributors who influence public opinion than the average, use them to increase your visibility! -> the data being probably anonymized for the employees to share, it would then be necessary to have a system that asks the employee if he agrees that his identity is revealed to his employer who is looking for Active contributors who influence public opinion like him/her.)
- Beware, more than half of your employees are unstable in their career (average observed in other companies < 28%), you risk a high turnover

2. add up the connections, deduplicate them and realize the potential reach of the company's employees to intelligently involve them in the activation of this collective network + potentially map who is reaching whom
3. Aggregate the add targeting criteria of the employees to draw nice external and/or internal communication contents showing the diversity of the company, its global geographical location, the incredible amount of diplomas/experiences/skills accumulated... 

According to https://github.com/hestiaAI/clients/issues/82 it would be nice to have it ready the 15th so that PO can demonstrate it during his lunch on the 16th and we can do a #DigipowerLive with it on the 17th.

**Comment by pdehaye** [comment]
I think the big question is aggregation for whom? A teacher? The company? A consultant the company is hiring? Very hard to say actually!!! All sound interesting in some way!
