### ISSUE TITLE
Accessors for the file explorer

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#265]
(I'm leaving this text as it is. Meanwhile bookmarks have been renamed to accessors, and newer comments have the latest information)

(This is what a remember from a discussion with @pdehaye in the train this morning. Unfortunately, it is now inextricably mixed up with my thoughts about how to name and implement it.)

Allow users to pinpoint interesting places in their data,
so they can find it again and share it.

A bookmark is made of

1.  the location of the file in the zip (a unix path)
2.  if needed: the location of the data in the file (jsonpath for json)
3.  the structure of the data (jsonschema for json?, maybe for csv too?)
4.  if needed: ui to display it, but maybe that can be inferred from its structure? (table, list, tree)

@emmanuel-hestia, maybe you have ideas for better formats to encode this data, I haven&rsquo;t looked into all the possibilities of json-ld etc&#x2026;

# Defining a bookmark

The file explorer ui lets the user set bookmarks. A node in the tree-viewer defines 1. and 2., we just need to add a button or a checkbox to add a bookmark.

We need and additional ui to define 3. and 4.

A list of json objects that all have some keys in common (ad impressions for one advertiser) could be displayed as a table. Hiding a column would indicate that attribute should not be shared. This data would have the type of an array of objects, which we could decide to display by default as a table. The exact jsonschema of the resulting json could be inferred with a library like [quicktype](https://github.com/quicktype/quicktype).

A single json object could be displayed with checkboxes next to each property.

It might make sense to give the user the option two switch between a tree and a table. Some lists will contain objects with children, or very disparate objects with few keys in common. Maybe there&rsquo;s a way to deal with that by having trees in table rows, but too much of that risks looking ugly. If the user can choose the ui, his choice must be indicated in part 4. of the bookmark. (Could this be some kind of annotation on the schema?)

(Note that if we define things this way, the place where data location ends and data structure starts is defined arbitrarily by the user. Hopefully this won&rsquo;t cause us too many headaches?)

# Bookmarks component / interaction with file explorer

The bookmarks themselves are displayed above the file explorer.
Clicking on a bookmark displays the bookmarked place in the explorer. Several bookmarks can be selected at the same time.

# Export / import

The selected bookmarks can be downloaded as a json, with or without the data they reference. The json can be included in the exported/encrypted zip file.

A bookmark json can be uploaded to an experience. If it contains only the bookmarks, display what&rsquo;s at the bookmarks in the current data.

If it contains data, maybe display that and throw out the previously uploaded data.

# Other ideas

## Reuse types

We might have a list of impressions in a folder for one advertiser, and another list of the same type in another&rsquo;s advertiser&rsquo;s folder.

It might be practical for the user who has defined a type for one advertiser&rsquo;s list, to reuse it for the other advertisers, for example if there&rsquo;s one field he wants to exclude.

## Linking bookmarks

An attribute might be like a foreign key to another type, somewhere else in the json. Paul-Olivier talks about having something like an ORM. We could use that to load the data in a database and make requests on it. Could this be used as a tool to define a sql pipeline?

**Comment by andreaskundig** [comment]
More about schemas, formats to define them etc... at [schema.org](https://schema.org/docs/developers.html)

A [json-ld tutorial](https://medium.com/@kidehen/simple-linked-data-deployment-tutorial-using-json-ld-notation-3e753a5d44a3) recommended by  @emmanuel-hestia

**Comment by pdehaye** [comment]
First off, @andreaskundig, great work capturing many ideas (and pushing some further) in a conversation that was very intense and very unidirectional. Thanks. 

Another name for bookmarks might be "accessor" (cf. "mutator") or "lens"/"optics" (see [Design your optics for modularity](https://slides.yowconference.com/yowlambdajam2016/Hales-DesignYourOwnOptics.pdf?feature=oembed) and [Modular Data Accessor](https://mpickering.github.io/papers/profunctor-options.pdf)), or when talking about groups of lenses "traversals". "Bookmark" taps into a lot of our UX/UI experience on how it is used/displayed, which we might want to detach from in order to really explore the potential. I think a more "backend"-like term is more appropriate for that.   

A few additional remarks to understand the potential:
- traversals can be made to be composable ("accessor/to/file" + "traversal/in/JSONPath/to/interesting/place/*/" + "accessor/to/attribute/in/JSONPath/" + "{day}/{month}/{year}" accessor)
- you can do arithmetic with them, at least mentally   "JSONPath/to/Type1Object/*/" -  "JSONPath/to/Type1Object/*/Type2Object/*/" = gives a way to compute links between objects of the two types
- if I understand this correctly, there is a duality that allows to see the specification of a lens as the specification of a so-called "prism", which can handle some forms of inconsistencies in the data (with Maybe's, Either's, etc). This could be useful to validate the data that matches some criteria. 
- this might be very relevant to a consent form as well "upload all that match this traversal specification" (conceptually unifying traversals of the file system, the files themselves, or even digging into parsing of values). 
- more ambitious/long term: these concepts might be useful once we go (if ever) into a mode "do your own MitM on your browser/phone, we build the interface to help you figure out what goes through 

Next steps:
- The shex group had a way to specify file traversals. Not sure why they needed their own, but still we should look it up because their use case is the same as ours. 
- Upgrade the date viewer to include the bookmark/JSONPath associated to a particular date. This will help us very generically understand where/how there might be benefits in this approach.
- Think a bit around the Twitter experience, since it is the richest so far. What would these concepts have brought to us there? 
- Think a bit around the Facebook experience, since it has a lot of data and we haven't necessarily done too much there. What would these concepts bring?

**Comment by andreaskundig** [comment]
(after another meeting with  @pdehaye)

### Clarifications about @pdehaye's last comment

#### Composability
Composability refers to the possibility of having several relative file paths that result in another path when concatenated. JsonPath can be relative too.

An accessor should be able to contain several levels of relative paths,
where each level could be several relative paths

- /animal/
 - cat
  - .name
  - .favoriteFood
 - dog
  - .house
 - worm
  - .length
  
 (this is just a compressed form of a list of paths) 
 
#### Arithmetic
The idea is that given the accessors path1 and path2, you can obtain the relative path from one to another by subtraction: path2 - path1

path2 = path1 + (path2 - path1)

### Use cases

##### Highlight location of data in file explorer. 
Clicking an accessor displays in the file explorer. Share accessors as way of showing where relevant data can be found.

##### define data to export
Instead of just files to include in consent, specify what parts of the file to include.

#### define concepts like geolocalization, ad-tracking
Accessors to all the data relevant to one topic define a concept.
This makes it easier for users to define what data they agree to share, and communicate to the developers what data they can work with.

#### define what data a pipeline/visualization needs
A pipeline could define the data it needs as a list of accessors. They could be run on the data extracted by the accessors selected by the user to determine if the pipeline can be run.

(Matching the accessors directly would be tricky because JSONPath allows to define the same paths in different ways)

Knowing which pipeline can be run would tell us which visualizations can be shown. 

In the case of pipeline that puts all the data in a database and then makes different queries on it for each viz, we would have either all or none. We could build different database for different queries, but this would slow the processing down. Maybe we could build an incomplete database if there's less input data, and check if it's complete enough for each separate query, but this sounds complicated.


### Next steps

In the date viewer, display the accessor for each date found. See how this helps or could have helped for twitter or facebook.

The only place where the date viewer displays dates separately is in the table, where the description already shows the path to the date (in readable non-jsonpath syntax)

What does this bring us?

**Comment by pdehaye** [comment]
@streitlua have you already made changes that I had suggested? What does this mean? "where the description already shows the path to the date (in readable non-jsonpath syntax)"

**Comment by andreaskundig** [comment]
Some excerpts from signal messages before I have time to flesh this out

@andreaskundig:
 
Finalement je me suis rendu compte qu'on utilise de l'information composée de path+jsonpath+structure a plusieurs endroits, et chaque fois d'une manière extrêmement différente qu'on aurait grand avantage a standardiser et generaliser. 

@pdehaye:
 
peut on lister tous les endroits ou de tels chemins apparaissent?

le but serait bien sur de mieux comprendre, mais ca nous ouvre aussi une perspective sur la question suivante: en conjonction avec quoi est-ce utilise?



@andreaskundig 

Très concrètement ici: pour dire à la pipeline sql comment créer des tables, et au date viewer de google ou chercher des dates. Donc on peut commencer par définir un format d'accesseurs qui généralise au maximum ces deux processus, ensuite on crée un ui pour fabriquer des accesseurs de ce format dans le date viewer et le file explorer, et on a immédiatement un outil qui facilite la création de nouveaux date viewers spécialisés, et de nouvelles pipelines sql.`

**Comment by streitlua** [comment]
> @streitlua have you already made the improvements that I had suggested on the date viewer?

Not yet, your suggestion is to show in the table an extra column "path"? I am not sure if this would be beneficial for the users.

>> where the description already shows the path to the date (in readable non-jsonpath syntax)

> What does this mean?

I think it's a reference to the current version of the date viewer that shows a "human readable path" as part of the description, as: 
![image](https://user-images.githubusercontent.com/16099301/145045753-10014527-8f24-49e4-b9f8-a6db1a8bcbd8.png)

**Comment by pdehaye** [comment]
@streitlua to some power users (3 more in the team) it would be neficial, as they would be able to guess the proper generalization with wildcards that would enable fetching all the objects of a certain type. we can have all three: machine readable path, human readable path and finally the actual string for the object. please split those into separate columns as it will allow evolving the thing with column-specific search etc.

**Comment by valentinoli** [comment]
@andreaskundig @pdehaye 
What is the status of this one? Can it be closed?

**Comment by alexbfree** [comment]
no longer needed
