### ISSUE TITLE
Problems displaying accented/special characters in our experiences

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#374]
We noticed several places where accented characters (e.g. as experienced in Finnish) were garbled/not displayed correctly throughout the experiences. Please let me know if you need test data.

**Comment by alexbfree** [comment]
Upon trying to produce test data for this, I see that unfortunately the bad characters eg `ElÃ¤in`, `YrittÃ¤jyys`, `Ãlykkyys`, `YmpÃ¤ristÃ¶`, are present saved into the `blockXX.json` file - I don't have the source data so can't tell if those errors were present in the source data or caused by an initial rendering problem on our side then saved on export.

That was the only test data I had so I will close this ticket and re-open if we see this again and can definitively show it's not an error in source data.

**Comment by ffsinger** [comment]
@streitlua what was the reason for having a map {filename->preprocessor}, instead of using the same preprocessor for all files (and maybe doing operations for a specific file in an `if` inside the preprocessor function) ? To solve this issue I think it would be simpler to have just one preprocessor for Facebook, instead of having a default one and specific ones for the files

**Comment by streitlua** [comment]
@ffsinger the mapping of a preprocessor per file allowed for a more granular control, but it is indeed a good idea to have a default preprocessor in some cases

**Comment by andreaskundig** [comment]
We could have done the mapping to the file name with a regex or a glob so we could choose either way through configuration
