### ISSUE TITLE
Create a test that runs the whole application

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#410]
The test would just make sure that the app runs and displays the starting page. It will be a starting point for writing other tests that simulate user interaction.

**Comment by ffsinger** [comment]
This can either be achieved with an end-to-end test framework, which were discussed in #191, or by writing a lot of component unit tests (difficult)

**Comment by andreaskundig** [comment]
This a duplicate of #191 actually, I'll close it. 

I would expect that there's something in between e2e running in a browser, and component tests for every single component. 

There should be a way to instantiate the top component App and let it instantiate all its children. This is trivial to do in react, why would vue not have this very important feature?

I would recommend to try this first, and if it turns out to be difficult after all, use e2e testing.

**Comment by ffsinger** [comment]
> There should be a way to instantiate the top component App and let it instantiate all its children. This is trivial to do in react, why would vue not have this very important feature?

You're right, when we use the `mount` function of `vue-test-utils`, it also mounts the children (as opposed to `shallowMount`). It may not be a best practice to write assertions for the children components, that's why I was suggesting writing unit tests for each of them. But here you're suggesting to have a test that just loads the starting page so it's not a problem

Note that the snapshots, however, will not render the HTML of the children
