### ISSUE TITLE
Visual problems with experience tabs

### ISSUE THREAD

**Issue by streitlua** [hestiaAI/hestialabs-experiences#438]
If the title of a sub-experience is too long, it doesn't appear correctly:
![image](https://user-images.githubusercontent.com/16099301/148189075-aad1591f-2398-4168-bd92-fa39caaf24dd.png)

And btw, good job! This looks great!

**Comment by valentinoli** [comment]
Ah, ok. The tabs are equal width. I don't think it would look nice to allow tabs to have different sizes depending on the size of the title. The only solution I see here is to shorten the title.

**Comment by alexbfree** [comment]
Can we add a mechanism to abbreviate the tab name with ellipsis (...) when it is too long so that this unsightly overflowing name issue can never occur? 

I agree though that in practice that using short tab names would result in a better user experience, abbreviated tab names would not be useful.

Does this imply that each tab needs two names, a "short name" (used in tab) and a "full name" (used as title within the tab?)

**Comment by valentinoli** [comment]
yes, we can probably hide overflow and insert an ellipsis with CSS

**Comment by valentinoli** [comment]
> Does this imply that each tab needs two names, a "short name" (used in tab) and a "full name" (used as title within the tab?)

I don't know, you tell me. It is no problem to add an optional `shortTitle` field that would take precedence over the (longer) `title`. How would you shorten "Advertisers using your activity or information"? Maybe, "Advertisers using your data"?

**Comment by valentinoli** [comment]
Ok, then what remains is to rename longer titles - who should do that?
